#!/bin/bash

PORT='7051'
SERVICE=analysis_book
SERVICE_DIR=/kb/deployment/services/$SERVICE

if [ $# -gt 0 ]; then
    PORT=$1
fi

if [ ! -f $SERVICE_DIR/service.$PORT.pid ]; then
   echo "No pid file $SERVICE_DIR/service.$PORT.pid found for service $SERVICE" 1>&2
   exit 1
fi

PID=`cat $SERVICE_DIR/service.$PORT.pid`
kill $PID
rm $SERVICE_DIR/service.$PORT.pid
