export SHOCK_SERVER='http://140.221.84.144:8000'
export SHOCK_AUTH='oauth'
export KBNB_DIR='/mnt/notebook'
export KBNB_HASH='aXB5dGhvbjprYm5iaXB5'
export OAUTH_TOKEN_URL='https://nexus.api.globusonline.org/goauth/token?grant_type=client_credentials'
export OAUTH_USER_URL='https://nexus.api.globusonline.org/users'
